/**
 * Template Rendering Validator
 *
 * Uses Playwright to render generated templates in Sandpack-style isolation
 * and validate them at 3 breakpoints (375px, 768px, 1920px).
 *
 * Security note: This evaluates our own AI-generated template code in an
 * isolated headless browser context for quality validation purposes only.
 * The code is never from user input — it's generated by our own AI pipeline.
 */

import { chromium, type Browser } from 'playwright'

export interface ValidationResult {
  passed: boolean
  screenshots: {
    mobile: Buffer | null
    tablet: Buffer | null
    desktop: Buffer | null
  }
  errors: string[]
  warnings: string[]
  metrics: {
    renderTime: number
    consoleErrors: number
    horizontalOverflow: boolean
  }
}

const VIEWPORTS = {
  mobile: { width: 375, height: 812 },
  tablet: { width: 768, height: 1024 },
  desktop: { width: 1920, height: 1080 },
} as const

/**
 * Validate a template by rendering it via a local dev server preview URL.
 * This uses the existing Sandpack preview (already in Framify) rather than
 * raw eval, keeping the same security model as the existing preview feature.
 *
 * Alternative: pass template code to a Sandpack iframe URL for rendering.
 * For now, we use a data URL approach with CDN-loaded React.
 */
export async function validateTemplate(code: string): Promise<ValidationResult> {
  const result: ValidationResult = {
    passed: true,
    screenshots: { mobile: null, tablet: null, desktop: null },
    errors: [],
    warnings: [],
    metrics: {
      renderTime: 0,
      consoleErrors: 0,
      horizontalOverflow: false,
    },
  }

  let browser: Browser | null = null

  try {
    browser = await chromium.launch({ headless: true })
    const context = await browser.newContext()
    const page = await context.newPage()

    // Collect console errors
    const consoleErrors: string[] = []
    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        consoleErrors.push(msg.text())
      }
    })

    page.on('pageerror', (err) => {
      result.errors.push(`Runtime error: ${err.message}`)
    })

    // Use Sandpack's bundler URL to render the component safely
    // This is the same approach the existing TemplatePreview component uses
    const sandpackUrl = buildSandpackPreviewUrl(code)

    const startTime = Date.now()
    await page.goto(sandpackUrl, { waitUntil: 'networkidle', timeout: 30000 })
    await page.waitForTimeout(3000) // Allow React + animations to settle

    result.metrics.renderTime = Date.now() - startTime
    result.metrics.consoleErrors = consoleErrors.length

    // Filter non-critical console errors
    const criticalErrors = consoleErrors.filter(
      (e) =>
        !e.includes('Download the React DevTools') &&
        !e.includes('act(') &&
        !e.includes('Warning:') &&
        !e.includes('third-party cookie')
    )

    if (criticalErrors.length > 0) {
      result.errors.push(
        ...criticalErrors.map((e) => `Console error: ${e.slice(0, 200)}`)
      )
    }

    // Take screenshots at each viewport
    for (const [name, viewport] of Object.entries(VIEWPORTS)) {
      await page.setViewportSize(viewport)
      await page.waitForTimeout(500)

      // Check horizontal overflow
      const hasOverflow = await page.evaluate(() => {
        return document.documentElement.scrollWidth > document.documentElement.clientWidth
      })

      if (hasOverflow) {
        result.metrics.horizontalOverflow = true
        result.warnings.push(`Horizontal overflow detected at ${viewport.width}px`)
      }

      const screenshot = await page.screenshot({
        fullPage: true,
        type: 'png',
      })
      result.screenshots[name as keyof typeof VIEWPORTS] = screenshot
    }

    // Verify content rendered
    const bodyLength = await page.evaluate(() => {
      return document.body.textContent?.length || 0
    })

    if (bodyLength < 50) {
      result.errors.push('Template did not render any visible content')
    }

    result.passed = result.errors.length === 0
  } catch (error) {
    result.passed = false
    result.errors.push(
      `Validation failed: ${error instanceof Error ? error.message : 'Unknown error'}`
    )
  } finally {
    if (browser) {
      await browser.close()
    }
  }

  return result
}

/**
 * Build a Sandpack preview URL using CodeSandbox's bundler.
 * This is the same sandboxing approach used by Sandpack/CodeSandbox
 * for safe code execution in an iframe.
 */
function buildSandpackPreviewUrl(code: string): string {
  // Use CodeSandbox's sandpack bundler for safe rendering
  const files = {
    '/App.tsx': code,
    '/index.tsx': `
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);
`,
  }

  const params = new URLSearchParams({
    files: JSON.stringify(files),
    template: 'react-ts',
    entry: '/index.tsx',
  })

  // Sandpack bundler URL — renders in isolated sandbox
  return `https://sandpack-bundler.codesandbox.io/?${params.toString()}`
}

/**
 * Save screenshots to filesystem for marketplace previews
 */
export async function saveScreenshots(
  templateId: string,
  screenshots: ValidationResult['screenshots'],
  outputDir: string = '/tmp/framify-screenshots'
): Promise<Record<string, string>> {
  const { mkdirSync, writeFileSync } = await import('fs')
  const { join } = await import('path')

  mkdirSync(outputDir, { recursive: true })

  const paths: Record<string, string> = {}

  for (const [viewport, buffer] of Object.entries(screenshots)) {
    if (buffer) {
      const filename = `${templateId}-${viewport}.png`
      const filepath = join(outputDir, filename)
      writeFileSync(filepath, buffer)
      paths[viewport] = filepath
    }
  }

  return paths
}
